-- this is a comment

CREATE TABLE table_name (
	column1 integer NOT NULL PRIMARY KEY,
	column2 varchar(20),
	column3 timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	column4 smallint CHECK (column4 >= 0),
	CONSTRAINT ct1 CHECK (column4 IS NULL OR column2 IS NOT NULL)
);

INSERT INTO table_name (column1, column2, column3, ...)
VALUES (value1, value2, value3, ...);

BEGIN;
	UPDATE table_name
	SET balance = balance - 100.0
	WHERE account_id = '123';
-- more comment
COMMIT;

CREATE TABLE other_table (
	col1 int4 NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	col2 integer REFERENCES table_name
);

